### ISSUE TITLE
Parser extracts wrong Arch version numbers when containing git information

### ISSUE THREAD

**Issue by Whissi** [AMDmi3/repology#127]
See
 - http://repology.org/metapackage/gnome-shell/versions
 - http://repology.org/metapackage/atk/versions
 - http://repology.org/metapackage/mutter/versions

 ...and many other packages.

Arch Linux version for *gnome-shell* is `3.22.2+18+gdf7727a-1` but Repology sees only `18+gdf7727a-1`.

This causes all other distributions to appear outdated.

**Comment by AMDmi3** [comment]
Nice catch! Arch parser contains a bug which picks a version part right of ```+``` while it should pick a left part. I'll fix it ASAP.

**Comment by AMDmi3** [comment]
Deployed.
