### ISSUE TITLE
Version miscomparation

### ISSUE THREAD

**Issue by AMDmi3** [AMDmi3/repology#16]
autossh: 1.4c > 1.4e ???
lsof: 4.89 > 4.90.f ???

**Comment by alexws54tk** [comment]
У пакетов, версии которых **заканчиваются на букву**, буквы добавляют по-порядку от „**A**“ до „**Z**“.
* `timezone-data`: 2016e ->2016f ->2016g
* `openssl`: 1.0.2h -> 1.0.2i -> 1.0.2j
* `autossh`: 1.4c -> 1.4d -> 1.4e
* про `lsof` сказать такого не могу, по крайней мере автор так не нумерует.
* возможно ещё есть такие пакеты, но, подразумеваю, их количество ничтожно мало.

**Comment by AMDmi3** [comment]
The problem is that ```pkg_resources.parse_version``` does not work correctly in some cases. Not sure how it handles letters, but ```4.89 > 4.90.f``` case is an error despite how you look at it. I've added tests in 0668d4ded6b1cfcc8a4efde705a8a3b6ffdbfcac and there's known to be correct implementation - [pkg version -t](https://github.com/freebsd/pkg/blob/master/libpkg/pkg_version.c#L161) from FreeBSD. It's not too hard to port onto python.

PS. Please use English, this is international project.
