### ISSUE TITLE
Slackbuilds prg.info can have multiple download links

### ISSUE THREAD

**Issue by aclemons** [AMDmi3/repology#172]
The parser currently iterates by line to parse the download links, but some slackbuilds have multiple source links in the info file.

Note the broken links here: https://repology.org/metapackage/virtualbox/packages
ref: https://slackbuilds.org/slackbuilds/14.2/system/virtualbox/virtualbox.info

**Comment by AMDmi3** [comment]
This is known low priority problem, see #67. I think I'll fix it now.

**Comment by AMDmi3** [comment]
Fixed
