### ISSUE TITLE
Add KDE neon

### ISSUE THREAD

**Issue by jriddell** [AMDmi3/repology#173]
The latest and greatest from KDE

https://packaging.neon.kde.org/
https://community.kde.org/Neon/Git

uses .deb packages

**Comment by AMDmi3** [comment]
I don't see how to parse these. For instance, according to repology, [kcalc](https://repology.org/metapackage/kcalc/versions) latest version is 16.12.2. These repos, however, don't even have tags since 16.08. Downloading each repo and looking into changelog is not an option IMO.

**Comment by AMDmi3** [comment]
Oh, it turned out there's debian repo. Support added with #173

**Comment by jriddell** [comment]
KDE neon has appeared at https://repology.org/metapackage/okular/versions but no content yet, I'll be patient incase it needs an update

You probably want to use the Neon/release branches to get the most relevant version.

**Comment by AMDmi3** [comment]
> KDE neon has appeared at https://repology.org/metapackage/okular/versions but no content yet, I'll be patient incase it needs an update

Yes, it'll catch up in an hour

> You probably want to use the Neon/release branches to get the most relevant version

I'm not using any git repos, I'm using debian-like package repository from http://archive.neon.kde.org/user/dists/xenial/main/source/Sources.gz as suggested in the referenced PR. There are other repos there though.

**Comment by jriddell** [comment]
thanks!
(hastily running cleanup to remove old packages)
