### ISSUE TITLE
Same name, different package (whereami)

### ISSUE THREAD

**Issue by kootenpv** [AMDmi3/repology#180]
I noticed I got some traffic from repology for the package whereami

This is the repology link: https://repology.org/metapackage/whereami/versions

Only the AUR package was made by someone for the package [whereami](https://github.com/kootenpv/whereami) that I created. 

In the other package managers, it is actually different software.

I couldn't find a "report" link on the repology page of my package, it might be useful to add it.

**Comment by AMDmi3** [comment]
Fixed, thank you, whereami was split into whereami-kootenpv, whereami-debian, and whereami-pjp. The site will update in hours. Great idea about report form, I've added separate issue for it (#181).
