### ISSUE TITLE
Merge similar maintainers

### ISSUE THREAD

**Issue by AMDmi3** [AMDmi3/repology#34]
Merge maintainers case-insensitively, such as:

```
Debian JavaScript Maintainers <pkg-javascript-devel@lists.alioth.debian.org>
Debian Javascript Maintainers <pkg-javascript-devel@lists.alioth.debian.org>
```

**Comment by Whissi** [comment]
Don't forget to normalize e-mail addresses well.

**Comment by AMDmi3** [comment]
Sure, but could you please elaborate, I may be missing some knowledge here. I can thin of lowercase + removing part between ```+``` and ```@``` as in ```fabian+debian@greffrath.com```

**Comment by Whissi** [comment]
Go to http://beta.repology.org/maintainers/index.html and search for "nomial". You will find 2 matches: One where email address' local part is starting with a capital "P" and ending with a capital "C" (only 1 package) and the second one where the same email address consists only of small letters (89 packages).

When I reported this 3 days ago no link for this maintainer was working.

**Comment by AMDmi3** [comment]
That will be covered by case normalization.

**Comment by AMDmi3** [comment]
Done. Possible improvements listed in #92, #93.
