### ISSUE TITLE
Add Fedora packages

### ISSUE THREAD

**Issue by AMDmi3** [AMDmi3/repology#36]
Fetchable via web: https://admin.fedoraproject.org/pkgdb/packages/

Available for testing in `newrepos` branch. Still TODO:
- Improve fetching. Sequential fetching takes ~6 hours. Maybe do a parallel fetch.
- Improve parsing. Need more clever .spec parser which will be useful for other RPM repos.
  - Add substitution support (`Package: %foovar%`)
  - Fix parsing of multiline fields (`%description`)

**Comment by Conan-Kudo** [comment]
By the way, you could also use the Fedora [mdapi](https://apps.fedoraproject.org/mdapi/).

**Comment by AMDmi3** [comment]
Nice, but it provides too little info and doesn't seem to support batch mode.
