### ISSUE TITLE
Gentoo: parse all ebuilds?

### ISSUE THREAD

**Issue by AMDmi3** [AMDmi3/repology#59]

**Comment by alexws54tk** [comment]
If we will parse `.ebuild` files to, we will be able to obtain more information, than is in a `metadata.xml`, including [patches](https://github.com/AMDmi3/repology/issues/53#issuecomment-254798593).

**Comment by AMDmi3** [comment]
Yes. Gentoo parser obtains a lot of data from just directory structure and ```metadata.xml``` already, but ebuilds will additionally provide at least description, homepage and license information. Not that it's heavily used for now.

**Comment by alexws54tk** [comment]
[This](https://devmanual.gentoo.org/quickstart/index.html) and [this](https://devmanual.gentoo.org/ebuild-writing/index.html) links maybe help us.

**Comment by AMDmi3** [comment]
We rather need a way to parse them. It's plain shell, right? Just need a simple shell parser, which may come in use for parsing Arch PKGBUILDs as well. At first glance, no complex logic is needed, just need to grab variable assignments at root level. I hope using a function of conditional to set DESCRIPTION/HOMEPAGE/LICENSE is not very common in Gentoo/Arch, as well as referencing other variables.

**Comment by alexws54tk** [comment]
Yes. It`s plain shell.
```shell
…
DESCRIPTION="Exuberant ctags generates tags files for quick source navigation"
HOMEPAGE="http://ctags.sourceforge.net"
LICENSE="GPL-2"
…
```
This is mandatory fields in Gentoo `.ebuilds`, at least in the main repository and the main overlays.

**Comment by AMDmi3** [comment]
Still there are substitutions:

```
% find . -name "*.ebuild" -exec grep '^DESCRIPTION=.*\$' {} \;
DESCRIPTION="${PN} is a ncurses-based config management utility"
DESCRIPTION="Transition package moving to single ${CATEGORY}/oracle-instantclient package"
DESCRIPTION="Transition package moving to single ${CATEGORY}/oracle-instantclient package"
DESCRIPTION="Transition package moving to single ${CATEGORY}/oracle-instantclient package"
DESCRIPTION="${MY_PN} is a job scheduler for PostgreSQL"
DESCRIPTION="${MY_PN} is a job scheduler for PostgreSQL"
...
```

Even for licenses (x11-apps/xinit), and here LICENSE is previously defined by ```inherit xorg-2```
```
LICENSE="${LICENSE} GPL-2"
```

This is going to be comples, not sure if worth the effort.

**Comment by Whissi** [comment]
I don't recommend to try to parse our ebuilds. Yes, they are bash scripts, but are dynamic. Try to use our pre-generated metadata instead. For example, the metadata for oracle-instantclient ebuild from your example this would be https://github.com/gentoo-mirror/gentoo/blob/c29270a3d2cace24ca44e1bd0fd6e91676151e67/metadata/md5-cache/dev-db/oracle-instantclient-12.1.0.2:

```
DEFINED_PHASES=compile configure install postinst preinst prepare test unpack
DEPEND=app-arch/unzip
DESCRIPTION=Oracle 12c Instant Client with SDK
EAPI=6
HOMEPAGE=http://www.oracle.com/technetwork/database/features/instant-client/index.html
IUSE=jdbc odbc +sdk +sqlplus tools abi_x86_32 abi_x86_64 abi_x86_x32 abi_mips_n32 abi_mips_n64 abi_mips_o32 abi_ppc_32 abi_ppc_64 abi_s390_32 abi_s390_64
KEYWORDS=~amd64 ~x86
LICENSE=OTN
RDEPEND=>=dev-libs/libaio-0.3.109-r5[abi_x86_32(-)?,abi_x86_64(-)?,abi_x86_x32(-)?,abi_mips_n32(-)?,abi_mips_n64(-)?,abi_mips_o32(-)?,abi_ppc_32(-)?,abi_ppc_64(-)?,abi_s390_32(-)?,abi_s390_64(-)?] !<dev-db/oracle-instantclient-basic-12 !<dev-db/oracle-instantclient-odbc-12 !<dev-db/oracle-instantclient-jdbc-12 !<dev-db/oracle-instantclient-sqlplus-12
RESTRICT=fetch splitdebug
SLOT=0/12.1
SRC_URI=abi_x86_32? ( instantclient-basic-linux-12.1.0.2.0.zip odbc? ( instantclient-odbc-linux-12.1.0.2.0.zip ) jdbc? ( instantclient-jdbc-linux-12.1.0.2.0.zip ) !abi_x86_64? ( sdk? ( instantclient-sdk-linux-12.1.0.2.0.zip ) sqlplus? ( instantclient-sqlplus-linux-12.1.0.2.0.zip ) tools? ( instantclient-tools-linux-12.1.0.2.0.zip ) ) ) abi_x86_64? ( instantclient-basic-linux.x64-12.1.0.2.0.zip odbc? ( instantclient-odbc-linux.x64-12.1.0.2.0.zip ) jdbc? ( instantclient-jdbc-linux.x64-12.1.0.2.0.zip ) sdk? ( instantclient-sdk-linux.x64-12.1.0.2.0.zip ) sqlplus? ( instantclient-sqlplus-linux.x64-12.1.0.2.0.zip ) tools? ( instantclient-tools-linux.x64-12.1.0.2.0.zip ) )
_eclass_exported_funcs=pkg_preinst:- pkg_postinst:- src_unpack:- src_prepare:- src_configure:- src_compile:- src_test:multilib-minimal src_install:-
_eclasses_=eutils	b83a2420b796f7c6eff682679d08fe25	multibuild	742139c87a9fa3766f0c2b155e5522bf	multilib	165fc17c38d1b11dac2008280dab6e80	multilib-build	8fe2e81aeb36cdf8a6cc5f50443879cc	multilib-minimal	0224dee31c0f98405d572e14ad6dee65	pax-utils	4c2654a34ebe732e85fda354f6ee642f	toolchain-funcs	1b1da0c45c555989dc5d832b54880783	versionator	99ae9d758cbe7cfed19170e7d48f5a9c
_md5_=22a4acd1783c2cbf8cceddbaa2e61189
```

We also provide an API, see https://packages.gentoo.org/packages/dev-db/oracle-instantclient.json

**Comment by AMDmi3** [comment]
Thanks a lot, it's just what I need!
