### ISSUE TITLE
Trim maintainer names

### ISSUE THREAD

**Issue by AMDmi3** [AMDmi3/repology#61]
Leave only email and sanitize it (```foo at bar dot com```, ```foo[at]bar[dot]com``` -> ```foo@bar.com```), lowercase, possibly trim ```+```'s. May leave list of full names corresponding to maintainer somewhere.

**Comment by craftyguy** [comment]
I'm curious if something like this was implemented, translating `foo at bar dot com` --> `foo@bar.com`. It doesn't seem to be working for some packages I maintain in the AUR repo, since they don't show up when I do a 'maintainer' search for my email. I can file a new issue if that's helpful..

**Comment by craftyguy** [comment]
Ah nevermind, found this comment with your position on the matter: https://github.com/repology/repology-updater/issues/1054#issuecomment-635492647

Sorry for the noise.
