### ISSUE TITLE
0ad & 0ad-data in ArchLinux

### ISSUE THREAD

**Issue by DebugReport** [AMDmi3/repology#63]
http://beta.repology.org/package/0ad.html
Version in ArchLinux is 0.0.21-alpha not a21. But used a21 for package (see pkgver & _pkgver in PKGBUILD https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/0ad )

**Comment by AMDmi3** [comment]
Repology looks into package version. As I understand, _pkgver is only used internally in PKGBUILD and is not visible outside, and repology does not parse PKGBUILDs, it looks into package databases ```http://delta.archlinux.fr/core/os/x86_64/*.db.tar.gz```. I treat this as broken versioning scheme in Arch repository.
