### ISSUE TITLE
Add Mageia support

### ISSUE THREAD

**Issue by Conan-Kudo** [AMDmi3/repology#66]
Add support for processing Mageia repositories.

As of Mageia 6 and Cauldron, it offers repository metadata of the same type as Fedora (#36) and openSUSE (#44).

See the following:
* https://mirrors.kernel.org/mageia/distrib/6/
* https://mirrors.kernel.org/mageia/distrib/cauldron/

**Comment by AMDmi3** [comment]
In progress

**Comment by Conan-Kudo** [comment]
@AMDmi3 Cauldron is the development branch (like Rawhide for Fedora or Factory for openSUSE), so that's probably what you want to watch.

**Comment by AMDmi3** [comment]
I'm adding both 6 and Cauldron, the only problem is currently displaying all the repos in a single table, which grows larger than its bounds already. I'm adding Mageia Cauldron anyway, and next I think I'll work on some javascript to dymanically hide some columns. With it, it'll be possible to show all distros including stable versions.
